# Generated by Django 3.0.4 on 2020-05-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200517_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='country',
            new_name='country_code',
        ),
    ]
