# Generated by Django 3.0.4 on 2020-05-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200517_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_costumer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
