# Generated by Django 3.0.4 on 2020-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200329_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='book_list', to='products.Product'),
        ),
    ]
