# Generated by Django 3.0.4 on 2020-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200331_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=4),
        ),
    ]
